chat:
  available_models:
  - gpt-4o-mini
  - gpt-4
  - gpt-3.5-turbo
  model: gpt-4
  streaming: true
  temperature: 0.0
embeddings:
  available_models:
  - text-embedding-3-small
  - text-embedding-3-large
  - text-embedding-ada-002
  batch_size: 100
  chunk_overlap: 200
  chunk_size: 1200
  min_chunk_size: 700
  model: text-embedding-3-large
  rate_limit: 1
  tmp_directory: .retrievai/tmp
vectorstore:
  directory: .retrievai/db
  fetch_k: 20
  k: 10
  search_type: mmr
